# Generated by Django 2.2.6 on 2019-11-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
